generatorName: spring
generateApis: true
generateModels: true
generateSupportingFiles: false
generateApiTests: false
generateModelTests: false

configOptions:
  useSpringBoot3: "true"
  interfaceOnly: "true"
  skipDefaultInterface: "true"
  useTags: "true"
  useJakartaEe: "true"
  useBeanValidation: "true"
  performBeanValidation: "true"
  requestMappingMode: api_interface
  dateLibrary: java8
  openApiNullable: "false"
  hideGenerationTimestamp: "true"